# Generated by Django 4.1.5 on 2023-01-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0002_article_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(upload_to='all_files/'),
        ),
    ]
