# Generated by Django 4.1.5 on 2023-01-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searching', '0003_alter_article_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='views',
            new_name='downloads',
        ),
    ]
